amazon translate
sxtfv/flutter_arb_translator pull request #8
Opened 2023-12-14 20:15 UTC by veronikalaskova

Add AWS Amazon translate as another translation service option. 
Follows the same setup as other translation services.

2023-12-14 23:32 UTC, sxtfv requested changes
Thank you for adding Amazon translation to this project. I left some comments, which are mostly related to code formatting
Please update your PR and I will merge it

2023-12-14 23:32 UTC, sxtfv commented on lib/service/translation/amazon_translate.dart
> +import 'package:flutter_arb_translator/models/api_result.dart';
please use relative paths for in-project references:
`import '../../models/api_result.dart';`

2023-12-14 23:32 UTC, sxtfv commented on lib/service/translation/amazon_translate.dart
> +  final AmazonTranslateClient client;
I suppose `AmazonTranslateClient` should be private `_AmazonTranslateClient`

2023-12-14 23:32 UTC, sxtfv commented on lib/service/translation/amazon_translate.dart
> +    return apiResult.value!.translations.first.translatedText;
please use `apiResult.valueUnsafe`

2023-12-14 23:32 UTC, sxtfv commented on lib/service/translation/amazon_translate.dart
> +    return apiResult.value!.translations.map((e) => e.translatedText).toList();
please use `apiResult.valueUnsafe`

2023-12-14 23:32 UTC, sxtfv commented on lib/service/translation/amazon_translate.dart
> +class AmazonTranslateClient {
I suppose this class should be private `_AmazonTranslateClient`

2023-12-14 23:32 UTC, sxtfv commented on lib/service/translation/amazon_translate.dart
> +  factory AmazonTranslateClient.translate({
Shouldn't this factory method be called `create()`?

2023-12-14 23:32 UTC, sxtfv commented on lib/service/translation/amazon_translate.dart
> +  HttpClient buildClient(Logger logger, String message) {
Please update visibility of methods in this class
It looks like the only public method is `translate()`. If so, please modify other methods to be private, for example `buildClient()` -> `_buildClient()`, etc

2023-12-14 23:32 UTC, sxtfv commented on lib/service/translation/amazon_translate.dart
> +    print("translating messages: " + messages.join("\n"));
please remove this message or use logger

2023-12-14 23:32 UTC, sxtfv commented on lib/service/translation/amazon_translate.dart
> +class SourceData {
This class might be private

2023-12-14 23:32 UTC, sxtfv commented on lib/service/translation/amazon_translate.dart
> +class AmazonTranslationItem {
This class might be private as well

2023-12-15 00:32 UTC, veronikalaskova commented
Hi there, 
Thanks for the quick reply.
I've pushed a commit with the requested changes.

2023-12-15 00:53 UTC, sxtfv approved these changes
Thanks for updating the PR

2023-12-15 00:53 UTC, merged